# Generated by Django 4.1.3 on 2022-12-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('nome', models.CharField(max_length=300, verbose_name='Nome')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('sexo', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino'), ('N', 'Nenhuma das opções')], max_length=1)),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('estado_civil', models.CharField(choices=[('S', 'Solteiro(a)'), ('C', 'Casado(a)')], max_length=1, verbose_name='Estado Civil')),
                ('cep', models.CharField(blank=True, max_length=9, null=True, verbose_name='Cep')),
                ('endereco', models.CharField(max_length=200, verbose_name='Endereço')),
                ('zona', models.CharField(choices=[('U', 'Urbana'), ('R', 'Rural')], max_length=1, verbose_name='Zona')),
                ('nome_da_mae', models.CharField(max_length=300, verbose_name='Nome da Mãe')),
                ('nome_do_pai', models.CharField(max_length=300, verbose_name='Nome do Pai')),
                ('cpf_da_mae', models.CharField(max_length=11, verbose_name='CPF da Mãe')),
                ('cpf_do_pai', models.CharField(max_length=11, verbose_name='CPF do Pai')),
                ('responsavel', models.CharField(choices=[('P', 'Pai'), ('M', 'Mãe')], max_length=1, verbose_name='Responsável')),
            ],
        ),
    ]
