# Generated by Django 4.1.3 on 2022-12-17 13:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('nome', models.CharField(max_length=300, verbose_name='Nome')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('sexo', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino'), ('N', 'Nenhuma das opções')], max_length=1)),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('estado_civil', models.CharField(choices=[('S', 'Solteiro(a)'), ('C', 'Casado(a)')], max_length=1, verbose_name='Estado Civil')),
                ('cep', models.CharField(blank=True, max_length=9, null=True, verbose_name='Cep')),
                ('endereco', models.CharField(max_length=200, verbose_name='Endereço')),
                ('zona', models.CharField(choices=[('U', 'Urbana'), ('R', 'Rural')], max_length=1, verbose_name='Zona')),
                ('nome_da_mae', models.CharField(max_length=300, verbose_name='Nome da Mãe')),
                ('nome_do_pai', models.CharField(max_length=300, verbose_name='Nome do Pai')),
                ('cpf_da_mae', models.CharField(max_length=11, verbose_name='CPF da Mãe')),
                ('cpf_do_pai', models.CharField(max_length=11, verbose_name='CPF do Pai')),
                ('responsavel', models.CharField(choices=[('P', 'Pai'), ('M', 'Mãe')], max_length=1, verbose_name='Responsável')),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome Disciplina')),
                ('codigo', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Codigo')),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='sexo',
            field=models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino'), ('N', 'Nenhuma das opções')], default={' '}, max_length=1),
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300, verbose_name='Nome')),
                ('sala', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Sala')),
                ('turno', models.CharField(choices=[('M', 'Matutino'), ('V', 'Vespertino'), ('N', 'Noturno')], max_length=1)),
                ('tipo_atendimento', models.CharField(choices=[('1', 'Ensino Fundamental'), ('2', 'Ensino Médio')], max_length=1)),
                ('dia_semana', models.CharField(max_length=20, verbose_name='Dia da Semana')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.disciplina')),
            ],
        ),
    ]
