# Generated by Django 4.1.3 on 2022-12-16 17:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_aluno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome Disciplina')),
                ('codigo', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Codigo')),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300, verbose_name='Nome')),
                ('sala', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Sala')),
                ('turno', models.CharField(choices=[('M', 'Matutino'), ('V', 'Vespertino'), ('N', 'Noturno')], max_length=1)),
                ('tipo_atendimento', models.CharField(choices=[('1', 'Ensino Fundamental'), ('2', 'Ensino Médio')], max_length=1)),
                ('dia_semana', models.CharField(max_length=20, verbose_name='Dia da Semana')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.disciplina')),
            ],
        ),
    ]
