# Generated by Django 4.1.3 on 2022-12-18 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_aluno_disciplina_alter_usuario_sexo_turma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='estado_civil',
            field=models.CharField(choices=[('B', ''), ('S', 'Solteiro(a)'), ('C', 'Casado(a)')], default='B', max_length=1, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='responsavel',
            field=models.CharField(choices=[('B', ''), ('P', 'Pai'), ('M', 'Mãe')], default='B', max_length=1, verbose_name='Responsável'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='sexo',
            field=models.CharField(choices=[('B', ''), ('F', 'Feminino'), ('M', 'Masculino'), ('N', 'Nenhuma das opções')], default='B', max_length=1),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='zona',
            field=models.CharField(choices=[('B', ''), ('U', 'Urbana'), ('R', 'Rural')], default='B', max_length=1, verbose_name='Zona'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='tipo_atendimento',
            field=models.CharField(choices=[('B', ''), ('1', 'Ensino Fundamental'), ('2', 'Ensino Médio')], default='B', max_length=1),
        ),
        migrations.AlterField(
            model_name='turma',
            name='turno',
            field=models.CharField(choices=[('B', ''), ('M', 'Matutino'), ('V', 'Vespertino'), ('N', 'Noturno')], default='B', max_length=1),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='estado_civil',
            field=models.CharField(choices=[('B', ''), ('S', 'Solteiro(a)'), ('C', 'Casado(a)')], default='B', max_length=1, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='sexo',
            field=models.CharField(choices=[('B', ''), ('F', 'Feminino'), ('M', 'Masculino'), ('N', 'Nenhuma das opções')], default='B', max_length=1),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='zona',
            field=models.CharField(choices=[('B', ''), ('U', 'Urbana'), ('R', 'Rural')], default='B', max_length=1, verbose_name='Zona'),
        ),
    ]
