# Generated by Django 4.1.3 on 2022-12-20 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_aluno_estado_civil_alter_aluno_responsavel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='cpf',
            field=models.CharField(max_length=14, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='cpf_da_mae',
            field=models.CharField(max_length=14, verbose_name='CPF da Mãe'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='cpf_do_pai',
            field=models.CharField(max_length=14, verbose_name='CPF do Pai'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(max_length=14, verbose_name='CPF'),
        ),
    ]
