# Generated by Django 4.1.3 on 2023-01-28 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotacao',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotacoes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lotacao',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotacoes', to='core.turma'),
        ),
    ]
